routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DistrictController;
use App\Http\Controllers\DropDownController;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\LocalLevelController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('province', ProvinceController::class);
Route::resource('district', DistrictController::class);
Route::resource('locallevel', LocalLevelController::class);
Route::resource('dropdown', DropDownController::class);

Route::get('getdistrict', [DropDownController::class, 'getDistrict'])->name('getDistrict');
Route::get('getlocallevel', [DropDownController::class, 'getLocalLevel'])->name('getLocalLevel');

app/Models/Locallevel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Locallevel extends Model
{
    use HasFactory;
}

app/Http/Controllers/LocalLevelController.php
<?php

namespace App\Http\Controllers;

use App\Models\District;
use App\Models\Province;
use App\Models\Locallevel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\LocalLevelController;

class LocalLevelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['locallevels'] = DB::table('locallevels')
        ->join('districts', 'districts.id', '=', 'locallevels.district_id')
        ->join('provinces', 'provinces.id', '=', 'locallevels.province_id')
        ->get();
        return view('locallevel.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $province=Province::all();
        $district=District::all();
        return view('locallevel.create',compact('district','province'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([ 
            'locallevelname' => 'required',
            'province_id'  => 'required',
            'district_id' => 'required',
        ]);
        $locallevel = new Locallevel;
        $locallevel->locallevelname = $request->locallevelname;
        $locallevel->province_id = $request->province_id;
        $locallevel->district_id= $request->district_id;
        $locallevel->save();
        return redirect()->route('locallevel.index')
        ->with('success','Created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('locallevel.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/locallevel/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
    <form action="{{ route('locallevel.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="container">
            <strong>Province Name</strong>
                <select class="one" name="province_id">
                @foreach($province as $g)
                <option value="{{$g->id}}">{{$g->provincename}}</option>
                @endforeach
                </select><br>

            <strong>District Name</strong>
                <select class="one" name="district_id">
                @foreach($district as $g)
                <option value="{{$g->id}}">{{$g->districtname}}</option>
                @endforeach
            </select><br>
            
            <strong> Locallevel Name:</strong>
            <input type="text" name="locallevelname" class="form-control hello"  >
            @error('locallevelname')
            <div class="alert alert-danger mt-1 mb-1">{{$message}}</div>
            @enderror

            <input type="submit" value="submit" class="submitbtn">
        </div>
    </form>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

resources/views/locallevel/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <style>
      table,th,td
    {
      margin:80px;
      border:2px solid black;
      border-collapse:collapse;
      padding:10px;
      width:10%
    }
    th{
  text-align:center;
  color:white;
  background-color:#35586C;
}
td{
  color:blue;
  text-align:center;
}
      </style>
  </head>
<body>
<table class="table" style="width:60%">
  <thead>
    <tr>
      <th scope="col">Province Name</th>
      <th scope="col">District Name</th>
      <th scope="col">Locallevel Name</th>
    </tr>
  </thead>
  <tbody>
    @foreach($locallevels as $locallevel)
  <tr>
    
    <td>{{ $locallevel->provincename }}</td>
    <td>{{ $locallevel->districtname }}</td>
    <td>{{ $locallevel->locallevelname}}</td>
  </tr>
  @endforeach
 

  </tbody>
</table>
    
</body>
</html>