routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DistrictController;
use App\Http\Controllers\DropDownController;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\LocalLevelController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('province', ProvinceController::class);
Route::resource('district', DistrictController::class);
Route::resource('locallevel', LocalLevelController::class);
Route::resource('dropdown', DropDownController::class);

Route::get('getdistrict', [DropDownController::class, 'getDistrict'])->name('getDistrict');
Route::get('getlocallevel', [DropDownController::class, 'getLocalLevel'])->name('getLocalLevel');

app/Models/Province.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Province extends Model
{
    use HasFactory;
}

app/Http/Controllers/ProvinceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Province;
use Illuminate\Http\Request;
use App\Http\Controllers\ProvinceController;

class ProvinceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $data['provinces']= Province::all();
        return view('province.index',$data);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('province.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([ 
            'provincename' => 'required',
           
        ]);
        $province = new Province;
        $province->provincename = $request->provincename;
        $province->save();
        return redirect()->route('province.index')
        ->with('success','Created successfully');

        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('province.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function edit($id)
    // {
    //     return view('employee.edit');
    // }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function update(Request $request, $id)
    // {
    //     $request->validate([
    //         'provincename' => 'required',
    //     ]);
    //         $province = Province::find($id);
    //         $province->provincename = $request->provincename;
    //         $province->save();
    //         return redirect()->route('employee.index')
    //         ->with('success','employee Has Been updated successfully');
    // }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function destroy($name)
    // {
    //     $user = Province::find($name);
    //     $user->delete();
    //     return redirect()->route('employee.index')
    //     ->with('success',' has been deleted successfully');
    // }
}

resources/views/province/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
<form action="{{ route('province.store') }}" method="POST" enctype="multipart/form-data">
@csrf
<div class="container">
<strong> Province Name:</strong>
<input type="text" name="provincename" class="form-control hello"  >
@error('provincename')
<div class="alert alert-danger mt-1 mb-1">{{$message}}</div>
@enderror
<input type="submit" value="submit" class="submitbtn">
</div>
</form>
    
</body>
</html>

resources/views/province/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <style>
      table,th,td
    {
      margin:80px;
      border:2px solid black;
      border-collapse:collapse;
      padding:10px;
      width:10%
    }
    th{
  text-align:center;
  color:white;
  background-color:#35586C;
}
td{
  color:blue;
  text-align:center;
}
      </style>
</head>
<body>
  <div class= "container">
<table class="table" style="width:60%">
  <thead>
    <tr>
      <th scope="col">Province Name</th>
    </tr>
  </thead>
  <tbody>
    @foreach($provinces as $province)
  <tr>
    <td>{{ $province->provincename }}</td>
  </tr>
  @endforeach
 

  </tbody>
</table>
</div>
    
</body>
</html>