routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DistrictController;
use App\Http\Controllers\DropDownController;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\LocalLevelController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('province', ProvinceController::class);
Route::resource('district', DistrictController::class);
Route::resource('locallevel', LocalLevelController::class);
Route::resource('dropdown', DropDownController::class);

Route::get('getdistrict', [DropDownController::class, 'getDistrict'])->name('getDistrict');
Route::get('getlocallevel', [DropDownController::class, 'getLocalLevel'])->name('getLocalLevel');

app/Models/District.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class District extends Model
{
    use HasFactory;
}

app/Http/Controllers/DistrictController.php
<?php

namespace App\Http\Controllers;

use App\Models\District;
use App\Models\Province;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\DistrictController;

class DistrictController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['districts']= District::all();
        $data['districts'] = DB::table('districts')
        ->join('provinces', 'provinces.id', '=', 'districts.province_id')
        ->get();
        // $data['locallevels']= Locallevel::all();
         
        return view('district.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $province=Province::all();
        return view('district.create',compact('province'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([ 
            'districtname' => 'required',
            'province_id'  => 'required',
        ]);
        $district = new District;
        $district->districtname = $request->districtname;
        $district->province_id = $request->province_id;
        $district->save();
        return redirect()->route('district.index')
        ->with('success','Created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('district.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function edit($id)
    // {
    //     return view('employee.edit');
    // }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function update(Request $request, $id)
    // {
    //     $request->validate([
    //         'districtname' => 'required',
    //         'province_id'  => 'required',
    //     ]);
    //         $district = District::find($id);
    //         $district->districtname = $request->districtname;
    //         $district->province_id = $request->province_id;
    //         $district->save();
    //         return redirect()->route('employee.index')
    //         ->with('success','employee Has Been updated successfully');
    // }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function destroy($id)
    // {
    //     $user = District::find($name);
    //     $user->delete();
    //     return redirect()->route('employee.index')
    //     ->with('success',' has been deleted successfully');
    // }
}

resources/views/district/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
<form action="{{ route('district.store') }}" method="POST" enctype="multipart/form-data">
@csrf
<div class="container">
    <strong>Province Name</strong>
    <select class="one" name="province_id">
    @foreach($province as $g)
       <option value="{{$g->id}}">{{$g->provincename}}</option>
       @endforeach
</select><br>
<strong> District Name:</strong>
<input type="text" name="districtname" class="form-control hello"  >
@error('districtname')

<div class="alert alert-danger mt-1 mb-1">{{$message}}</div>
@enderror
<input type="submit" value="submit" class="submitbtn">
</div>
</form>
    
</body>
</html>

resources/views/district/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <style>
      table,th,td
    {
      margin:100px;
      border:2px solid black;
      border-collapse:collapse;
      padding:10px;
      
    }
    th{
  text-align:center;
  color:white;
  background-color:#35586C;
  
}
td{
  color:blue;
  text-align:center;
 
}

      </style>
</head>
<body>
<table class="table" style="width:60%">
  <thead>
    <tr>
      <th scope="col">Province Name</th>
      <th scope="col">District Name</th>
    </tr>
  </thead>
  <tbody>
    @foreach($districts as $district)
  <tr>
    
    <td>{{ $district->provincename }}</td>
    <td>{{ $district->districtname }}</td>
  </tr>
  @endforeach
 

  </tbody>
</table>
    
</body>
</html>