routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DistrictController;
use App\Http\Controllers\DropDownController;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\LocalLevelController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('province', ProvinceController::class);
Route::resource('district', DistrictController::class);
Route::resource('locallevel', LocalLevelController::class);
Route::resource('dropdown', DropDownController::class);

Route::get('getdistrict', [DropDownController::class, 'getDistrict'])->name('getDistrict');
Route::get('getlocallevel', [DropDownController::class, 'getLocalLevel'])->name('getLocalLevel');

app/Models/Dropdown.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dropdown extends Model
{
    use HasFactory;
}

app/Http/Controllers/DropDownController.php
<?php

namespace App\Http\Controllers;

use App\Models\District;
use App\Models\Dropdown;
use App\Models\Province;
use App\Models\Locallevel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Http\Controllers\DropDownController;

class DropDownController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $data['dropdowns'] = DB::table('dropdowns')
        ->select('dropdowns.id', 'districts.districtname','provinces.provincename','locallevels.locallevelname')
        ->join('districts', 'districts.id', '=', 'dropdowns.district_id')
        ->join('provinces', 'provinces.id', '=', 'dropdowns.province_id')
        ->join('locallevels', 'locallevels.id', '=', 'dropdowns.locallevel_id')
        
        ->get();
        // dd($data);
        return view('dropdown.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $provinces=Province::all();
        $district=District::all();
        $locallevel=Locallevel::all();
        return view('dropdown.dropdown', compact('district','provinces','locallevel'));
    }
    public function getDistrict(Request $request)
    {
        $district = DB::table('districts')
            ->where("province_id",$request->province_id)
            ->pluck("districtname","id");
            return response()->json($district);
    }
    public function getLocalLevel(Request $request)
    {
        $locallevel = DB::table('locallevels')
            ->where("district_id",$request->district_id)
            ->pluck("locallevelname","id");
            return response()->json($locallevel);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->request);
        $request->validate([ 
            'locallevel_id' => 'required',
            'province_id'  => 'required',
            'district_id' => 'required',
        ]);
        $dropdown = new Dropdown;
        $dropdown->locallevel_id = $request->locallevel_id;
        $dropdown->province_id = $request->province_id;
        $dropdown->district_id= $request->district_id;
        $dropdown->save();

        return redirect()->route('dropdown.index')
        ->with('success','Created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dropdown $dropdown)
    {
        // dd('ok');
        $dropdown->delete();
        return redirect()->route('dropdown.index')
        ->with('success','has been deleted successfully');
    }
}

resources/views/dropdown/dropdown.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title> Dependent Dropdown using Jquery Ajax </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h2>Dynamic Dependent Dropdown using Jquery Ajax</h2>
  <form action="{{ route('dropdown.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
    <div class="form-group">
      <label for="province">Province:</label>
   <select id="province" name="province_id" class="form-control">
        <option value="" selected disabled>Select Province</option>
         @foreach($provinces as $key => $province)
         <option value="{{$key}}"> {{$province->provincename}}</option>
         @endforeach
         </select>
    </div>
    <div class="form-group">
      <label for="district">District:</label>
      <select name="district_id" id="district" class="form-control"></select>
    </div>
  <div class="form-group">
      <label for="locallevel">LocalLevel:</label>
      <select name="locallevel_id" id="locallevel" class="form-control"></select>
    </div>
    <input type="submit" value="submit" class="submitbtn">
</form>
</div>
<script type=text/javascript>
  $('#province').change(function(){
  var provinceId = $(this).val(); 
  if(provinceId){

    $.ajax({
      type:"GET",
      url:"{{url('getdistrict')}}?province_id="+provinceId,
      success:function(res){        
      if(res){
        $("#district").empty();
        $("#district").append('<option>Select District</option>');
        $.each(res,function(key,value){
          $("#district").append('<option value="'+key+'">'+value+'</option>');
        });
      }else{
        $("#district").empty();
      }
      }
    });
  }else{
    $("#district").empty();
    $("#locallevel").empty();
  }  
  });
  $('#district').on('change',function(){
  var districtId = $(this).val();  
  if(districtId){
    $.ajax({
      type:"GET",
      url:"{{url('getlocallevel')}}?district_id="+districtId,
      success:function(res){        
      if(res){
        $("#locallevel").empty();
 $("#locallevel").append('<option>Select LocalLevel</option>');
        $.each(res,function(key,value){
          $("#locallevel").append('<option value="'+key+'">'+value+'</option>');
        });
      }else{
        $("#locallevel").empty();
      }
      }
    });
  }else{
    $("#locallevel").empty();
  }
  });
</script>

</body>
</html>

resources/views/dropdown/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <style>
      table,th,td
    {
      margin:80px;
      border:2px solid black;
      border-collapse:collapse;
      padding:10px;
      width:10%
    }
    th{
  text-align:center;
  color:white;
  background-color:#35586C;
}
td{
  color:blue;
  text-align:center;
}
      </style>
  </head>
<body>
  <table class="table" style="width:60%">
    <thead>
      <tr>
        <th scope="col">Province Name</th>
        <th scope="col">District Name</th>
        <th scope="col">Locallevel Name</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach($dropdowns as $dropdown)
        <tr>
          <td>{{ $dropdown->provincename }}</td>
          <td>{{ $dropdown->districtname }}</td>
          <td>{{ $dropdown->locallevelname}}</td>
          <td>
            <form action="{{ route('dropdown.destroy',$dropdown->id) }}" method="POST">
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete this?')">Delete</button>
            </form>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>
    
</body>
</html>